### ISSUE TITLE
Cadastro de turma

### ISSUE THREAD

**Issue by MaiconLan** [MaiconLan/facial-recognition-frontend#4]
Desenvolver a tela de cadastro e listagem de turma

**Comment by MaiconLan** [comment]
Desenvolvido CRUD de turma 6ea51c5f9a8844970e0c877026ef3dd30f9aa674

**Comment by renanzapelini** [comment]
**PONTOS A SEREM CORRIGIDOS**
1 - Modificar script da base para o campo finalizada por padrão ser "false". Caso o usuário selecione o checkbox ignorar o default e salvar como true;
2 - É possível adicionar/remover estudantes de uma turma/matéria finalizada. Não sei se seria o certo, mas talvez não seja necessário alterar.

Pontos observados e corrigidos:
Adicionado obrigatoriedade no campo professor;
Corrigido título da tela de busca de turmas.

Demais itens ja verificados.
